name: simulator
description: Simulator for PLC-14500

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  file_picker: ^5.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/button.png
    - assets/led_on.png
    - assets/led_off.png
    - assets/led_placeholder.png
    - assets/switch_on.png
    - assets/switch_off.png
